feature: add bytedance pico content
KhronosGroup/OpenXR-Inventory pull request #11
Opened 2022-11-15 09:31 UTC by Phoobobo

2022-11-17 03:23 UTC, Phoobobo commented
@rpavlik could you help to run the workflows and review?

2022-11-17 14:51 UTC, rpavlik commented
Yep, it looks good to me, I'm just waiting for the conformance listing to move from "in review" to "conformant" so that the link actually goes to something publicly visible.

2022-11-17 14:52 UTC, rpavlik approved these changes, later dismissed

2022-12-21 16:47 UTC, rpavlik requested changes

2022-12-21 16:47 UTC, rpavlik commented on runtimes/bytedance_pico.json
> +        "XR_FB_swapchain_update_state"
You're missing the closing `]`

2022-12-21 19:42 UTC, rpavlik submitted a review, later dismissed

2022-12-21 20:25 UTC, merged