Featured table more and added modal popups for runtime details
KhronosGroup/OpenXR-Inventory pull request #31
Opened 2023-04-04 17:25 UTC by dennyronngren

… up some unwanted line breaks in tables.

2023-04-27 17:55 UTC, rpavlik commented
oh this looks nice with the modals, though it looks like it breaks the links in  the extension lists

![image](https://user-images.githubusercontent.com/61129/234951140-d417aac9-42c3-4832-b4cf-75036e2cc93c.png)

2023-04-27 17:58 UTC, rpavlik requested changes
we need to figure out what to do with the main-body links.

2023-05-15 08:33 UTC, dennyronngren commented
> oh this looks nice with the modals, though it looks like it breaks the links in the extension lists
> 
> ![image](https://user-images.githubusercontent.com/61129/234951140-d417aac9-42c3-4832-b4cf-75036e2cc93c.png)

I think those could be removed, the information is in the main table header now. What do you think? (I already did the change locally... and it looks good to me, but thought we should chat about it first)

If not, it would link to the table headers (with the runtimes).

> we need to figure out what to do with the main-body links.

Agreed, I think the "Extension" and "Runtime" might be ok to delete if we go with the change above.

2024-09-03 23:59 UTC, BastiaanOlij commented
@dennyronngren were you still looking into this PR/have time to look into this, and could you rebase it?
Or would you be fine for me to take it over?

2024-09-09 20:40 UTC, dennyronngren commented
> @dennyronngren were you still looking into this PR/have time to look into this, and could you rebase it? Or would you be fine for me to take it over?

Please take it over if you like.

2026-02-17 15:01 UTC, fredinfinite23 commented
hey @BastiaanOlij . Wondering if this PR's still relevant.
Let me know if we can drop or if you'd still want to work on it.

CC: @dennyronngren

2026-02-17 22:40 UTC, BastiaanOlij commented
I don't think so, maybe there are some things we want to adopt from it but I think we've pretty much gone in a different direction.

2026-07-20 23:43 UTC, closed without merging